# Auto Update will automatically keep a PR up to date
# Trigger on specific branches to minimize workflow execution.
name: Auto Update

on: push

on:
  push:
    branches:
      - develop
      - main
      - 'feature/*'
      - 'release/*'

jobs:
  auto-update:
    name: Auto Update
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/auto-update@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

