name: Auto Merge Release (git flow)
on:
  create

jobs:
  develop:
    if: ${{ contains(github.ref, 'refs/heads/feature') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge features into develop
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Merge ${{ format(github.ref, 'refs/heads/') }} into develop"
          pr_body: "This PR was created by a workflow"
          pr_label: "git-flow"
  release:
    if: ${{ contains(github.ref, 'release') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge releases into main
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Merge ${{ format(github.ref, 'refs/heads/') }} into main"
          pr_body: "This PR was created by a workflow"
          pr_label: "git-flow"
      - name: Merge release into develop
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Merge ${{ format(github.ref, 'refs/heads/') }} into develop"
          pr_body: "This PR was created by a workflow"
          pr_label: "git-flow"
