name: Auto Merge Release (git flow)
on:
  create:
    branches:
      - release/*
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge release into main
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Merge ${{ github.ref }} into main"
          pr_body: "This PR was created by a workflow"
          pr_label: "git-flow"
      - name: Merge release into develop
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Merge ${{ github.ref }} into develop"
          pr_body: "This PR was created by a workflow"
          pr_label: "git-flow"
