name: Merge releases into develop
on:
  push:
    branches:
      - 'release/**'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge releases into develop
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Merge ${{ github.ref }} into develop"
          pr_body: "This PR was created by a workflow action"
          pr_label: "git-flow"
