name: sandbox
on:
  push:
jobs:
  sandbox:
    runs-on: ubuntu-latest
    steps:
      - name: Action Script
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(context);

