name: Tag Release
on:
  create:
    branches:
      - release/**
      - '!hotfix/**'

jobs:
  tag:
    if: ${{ contains(github.ref, 'release') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@hollanddd'

      - name: Setup git
        run: |
          git config user.name ${GITHUB_ACTOR}
          git config user.email "<>"

      - name: Bump version
        run: npm version ${GITHUB_REF:19}

      - name: Git push
        run: |
          git push --no-verify origin ${GITHUB_REF:11}
          git push --no-verify origin ${GITHUB_REF:19}

      - name: Merge releases into main
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "ci: merge release ${{ steps.ref_version.outputs.VALUE }} into main"
          pr_body: This PR was created by a workflow
          pr_label: git-flow

      - name: Merge releases into develop
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "ci: merge release ${{ steps.ref_version.outputs.VALUE }} into develop"
          pr_body: This PR was created by a workflow action
          pr_label: git-flow
