name: Tag Release
on:
  create:
    branches:
      - release/*
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build changelog
        id: build_changelog
        uses: ardalanamini/auto-changelog@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude: 'perf,other,breaking'

      - name: Create release
        id: create_release
        uses: zendesk/action-create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${GITHUB_REF:19}
          body: ${{ steps.build_changelog.outputs.changelog }}
          tag_schema: semantic

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@hollanddd'

      - name: Bump version
        run: npm version ${GITHUB_REF:19}

      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: git status
        run: git status

      - name: Commit new version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: bump to ${GITHUB_REF:19}
          commit_options: '--no-verify --signoff'
          file_pattern: package.json
          status_options: '--untracked-files=no'

      - name: Merge releases into main
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: 'Merge release ${GITHUB_REF} into main'
          pr_body: This PR was created by a workflow
          pr_label: git-flow

      - name: Merge releases into develop
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: Merge release ${GITHUB_REF:19} into develop
          pr_body: This PR was created by a workflow action
          pr_label: git-flow
