name: Tag Release
on:
  create:
    branches:
      - release/*
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Extract tag from ref
        id: release_version
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // version from refs/heads/release/x.x.x
            return {
              current: context.ref.substr(19, context.ref.length)
            }
      - uses: actions/checkout@v2
      - name: Build changelog
        id: build_changelog
        uses: ardalanamini/auto-changelog@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude: 'perf,other,breaking'
      - name: Create release
        id: create_release
        uses: zendesk/action-create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '${{ steps.release_version.outputs.result.current }}'
          body: ${{ steps.build_changelog.outputs.changelog }}
          tag_schema: semantic
      - name: Bump version
        uses: 'reedyuk/npm-version@1.1.1'
        with:
          version: ${{ steps.release_version.outputs.result }}
          git-tag-version: false
