name: Tag Release
on:
  push:
    branches:
      - release/*
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Export generated version
        id: tag_name
        run: |
          echo ::set-output name=new_tag::`cat package.json | jq -r .version`
        shell: bash
      - name: Build changelog
        id: build_changelog
        uses: ardalanamini/auto-changelog@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude: 'perf,other,breaking'
      - name: Create release
        id: create_release
        uses: zendesk/action-create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_name.outputs.new_tag }}
          body: ${{ steps.build_changelog.outputs.changelog }}
          tag_schema: semantic
      - name: Bump version
        users: 'reedyuk/npm-version@1.1.1'
        with:
          version: ${{ steps.create_release.outputs.current_tag }}
          git-tag-version: false
